language: generic
services:
  - docker
env:
  global:
  - |
    CWD="$TRAVIS_BUILD_DIR"
    DOCKER_REPO=ea31337/ea-tester:dev
  matrix:
  - BT_RUN="compile_ea ConvertTest.mq4 && run_backtest -m1 -e ConvertTest.mq4"
  - BT_RUN="compile_ea StatsTest.mq4 && run_backtest -m1 -e StatsTest.mq4"
  - BT_RUN="compile_ea SummaryReportTest.mq4 && run_backtest -m1 -e SummaryReportTest.mq4"
  - BT_RUN="compile_ea TickerTest.mq4 && run_backtest -m1 -d1-5 -e TickerTest.mq4"
before_script:
- docker pull $DOCKER_REPO
script:
- docker run -v "$PWD:/opt/EA31337-classes:ro" $DOCKER_REPO 'rsync -aru /opt/EA31337-classes "$EXPERTS_DIR"/;' $BT_RUN
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
